package closermeapp.Presentation.Views;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.*;

/**
 *
 * @author André
 */
public class PrincipalMenuView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalMenu
     */
    public PrincipalMenuView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        memberButton = new javax.swing.JButton();
        enterpriseButton = new javax.swing.JButton();
        callLogButton = new javax.swing.JButton();
        reportButton = new javax.swing.JButton();
        memberLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        callLogLabel = new javax.swing.JLabel();
        reportLabel = new javax.swing.JLabel();
        eventButton = new javax.swing.JButton();
        eventLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground( new java.awt.Color( 51, 153, 255 ) );
        jPanel1.setForeground( new java.awt.Color( 0, 102, 255 ) );

        memberButton.setText("Miembros");

        enterpriseButton.setText("Empresas");

        callLogButton.setText("Llamadas");

        reportButton.setText("Reportes");

        memberLabel.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/image/user-icon (1).png" ) ) ); // NOI18N

        enterpriseLabel.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/image/users-icon.png" ) ) ); // NOI18N

        titlePanel.setBackground( new java.awt.Color( 51, 153, 255 ) );

        titleLabel.setFont( new java.awt.Font( "Plantagenet Cherokee", 0, 48 ) ); // NOI18N
        titleLabel.setText( "Closerme" );

        iconLabel.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/image/logo.png" ) ) ); // NOI18N

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout( titlePanel );
        titlePanel.setLayout( titlePanelLayout );
        titlePanelLayout.setHorizontalGroup(
                titlePanelLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGroup( javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                                .addContainerGap( 98, Short.MAX_VALUE )
                                .addComponent( titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE )
                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                .addComponent( iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE )
                                .addGap( 32, 32, 32 ) )
        );
        titlePanelLayout.setVerticalGroup(
                titlePanelLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGroup( titlePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent( iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE ) )
                        .addGroup( javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                                .addContainerGap( 27, Short.MAX_VALUE )
                                .addComponent( titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE )
                                .addGap( 19, 19, 19 ) )
        );

        callLogLabel.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/image/telephone-icon.png" ) ) ); // NOI18N

        reportLabel.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/image/news-icon (1).png" ) ) ); // NOI18N

        eventButton.setText( "Eventos" );

        eventLabel.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/image/megaphone-icon.png" ) ) ); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap( 49, 49, 49 )
                                                .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.TRAILING )
                                                        .addComponent( memberButton )
                                                        .addComponent( memberLabel ) )
                                                .addGap( 55, 55, 55 )
                                                .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING, false )
                                                        .addComponent( enterpriseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE )
                                                        .addComponent( enterpriseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) )
                                                .addGap( 62, 62, 62 )
                                                .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.TRAILING, false )
                                                        .addComponent( reportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE )
                                                        .addComponent( reportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) )
                                                .addGap( 35, 35, 35 )
                                                .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                                        .addComponent( callLogButton, javax.swing.GroupLayout.Alignment.TRAILING )
                                                        .addComponent( callLogLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                .addGap( 38, 38, 38 )
                                                .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                                        .addComponent( eventLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE )
                                                        .addComponent( eventButton ) ) )
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap( 144, 144, 144 )
                                                .addComponent( titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) ) )
                                .addContainerGap( 78, Short.MAX_VALUE ) )
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent( titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE )
                                .addGap( 18, 18, 18 )
                                .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                        .addComponent( memberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE )
                                        .addComponent( enterpriseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE )
                                        .addComponent( callLogLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE )
                                        .addComponent( reportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE )
                                        .addComponent( eventLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) )
                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(memberButton)
                                        .addComponent(enterpriseButton)
                                        .addComponent( reportButton )
                                        .addComponent( callLogButton )
                                        .addComponent( eventButton ) )
                                .addGap( 122, 122, 122 ) )
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalMenuView().setVisible(true);
            }
        });
    }

    public JButton getCallLogButton() {
        return callLogButton;
    }

    public JButton getEnterpriseButton() {
        return enterpriseButton;
    }

    public JButton getEventButton() {
        return eventButton;
    }

    public JButton getMemberButton() {
        return memberButton;
    }

    public JButton getReportButton() {
        return reportButton;
    }


    // Variables declaration - do not modify
    private javax.swing.JButton callLogButton;
    private javax.swing.JLabel callLogLabel;
    private javax.swing.JButton enterpriseButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton eventButton;
    private javax.swing.JLabel eventLabel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton memberButton;
    private javax.swing.JLabel memberLabel;
    private javax.swing.JButton reportButton;
    private javax.swing.JLabel reportLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration
}
