package closermeapp.Presentation.Views.Enterprise;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;

/**
 *
 * @author André
 */
public class EmployeeRegistrationView extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeRegistrationView
     */
    public EmployeeRegistrationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        windowsPanel = new javax.swing.JPanel();
        employeeGeneralDataPanel = new javax.swing.JPanel();
        employeeNameLabel = new javax.swing.JLabel();
        employeeNameTextBox = new javax.swing.JTextField();
        employeeCellPhoneLabel = new javax.swing.JLabel();
        employeeRoleTextBox = new javax.swing.JTextField();
        employeeRoleLabel = new javax.swing.JLabel();
        employeeCellPhoneTextBox1 = new javax.swing.JTextField();
        buttonsPanel = new javax.swing.JPanel();
        RegisterEmployeeButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        enterprisePanel = new javax.swing.JPanel();
        addEnterpriseButton = new javax.swing.JButton();
        enterpriseComboBox = new javax.swing.JComboBox();
        enterpriseNameLabel = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        employeeGeneralDataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));

        employeeNameLabel.setText("Nombre:");

        employeeCellPhoneLabel.setText("Telefono:");

        employeeRoleLabel.setText("Puesto:");

        javax.swing.GroupLayout employeeGeneralDataPanelLayout = new javax.swing.GroupLayout(employeeGeneralDataPanel);
        employeeGeneralDataPanel.setLayout(employeeGeneralDataPanelLayout);
        employeeGeneralDataPanelLayout.setHorizontalGroup(
                employeeGeneralDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(employeeGeneralDataPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(employeeGeneralDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(employeeGeneralDataPanelLayout.createSequentialGroup()
                                                .addGroup(employeeGeneralDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(employeeNameLabel)
                                                        .addComponent(employeeCellPhoneLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(employeeGeneralDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(employeeNameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                                        .addComponent(employeeCellPhoneTextBox1)))
                                        .addGroup(employeeGeneralDataPanelLayout.createSequentialGroup()
                                                .addComponent(employeeRoleLabel)
                                                .addGap(13, 13, 13)
                                                .addComponent(employeeRoleTextBox)))
                                .addContainerGap())
        );
        employeeGeneralDataPanelLayout.setVerticalGroup(
                employeeGeneralDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(employeeGeneralDataPanelLayout.createSequentialGroup()
                                .addGroup(employeeGeneralDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(employeeNameLabel)
                                        .addComponent(employeeNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(employeeGeneralDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(employeeCellPhoneLabel)
                                        .addComponent(employeeCellPhoneTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(employeeGeneralDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(employeeRoleLabel)
                                        .addComponent(employeeRoleTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(14, Short.MAX_VALUE))
        );

        RegisterEmployeeButton.setText("Registrar");

        cancelButton.setText("Cancelar");

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
                buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(buttonsPanelLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(RegisterEmployeeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelButton)
                                .addGap(33, 33, 33))
        );
        buttonsPanelLayout.setVerticalGroup(
                buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(RegisterEmployeeButton)
                                        .addComponent(cancelButton))
                                .addContainerGap())
        );

        enterprisePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        addEnterpriseButton.setText("Registrar");

        enterpriseComboBox.setModel(new javax.swing.DefaultComboBoxModel());

        enterpriseNameLabel.setText("Empresas");

        javax.swing.GroupLayout enterprisePanelLayout = new javax.swing.GroupLayout(enterprisePanel);
        enterprisePanel.setLayout(enterprisePanelLayout);
        enterprisePanelLayout.setHorizontalGroup(
                enterprisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(enterprisePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(enterpriseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(enterpriseNameLabel)
                                .addGap(46, 46, 46)
                                .addComponent(addEnterpriseButton)
                                .addGap(24, 24, 24))
        );
        enterprisePanelLayout.setVerticalGroup(
                enterprisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterprisePanelLayout.createSequentialGroup()
                                .addComponent(enterpriseNameLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(enterprisePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(enterprisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addEnterpriseButton)
                                        .addComponent(enterpriseComboBox))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
                titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 366, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
                titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 26, Short.MAX_VALUE)
        );

        titleLabel.setText("Empleado");

        javax.swing.GroupLayout windowsPanelLayout = new javax.swing.GroupLayout(windowsPanel);
        windowsPanel.setLayout(windowsPanelLayout);
        windowsPanelLayout.setHorizontalGroup(
                windowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(windowsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(windowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, windowsPanelLayout.createSequentialGroup()
                                                .addGroup(windowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(employeeGeneralDataPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(enterprisePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(24, 24, 24))
                                        .addGroup(windowsPanelLayout.createSequentialGroup()
                                                .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())))
                        .addGroup(windowsPanelLayout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(titleLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        windowsPanelLayout.setVerticalGroup(
                windowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, windowsPanelLayout.createSequentialGroup()
                                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enterprisePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(employeeGeneralDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
        );

        getContentPane().add(windowsPanel);

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRegistrationView().setVisible(true);
            }
        });
    }

    public JButton getRegisterEmployeeButton() {
        return RegisterEmployeeButton;
    }

    public JButton getRegisterEnterpriseButton() {
        return addEnterpriseButton;
    }

    public JPanel getButtonsPanel() {
        return buttonsPanel;
    }

    public JButton getCancelButton() {
        return cancelButton;
    }

    public JComboBox getEnterpriseComboBox() {
        return enterpriseComboBox;
    }

    public JLabel getEnterpriseNameLabel() {
        return enterpriseNameLabel;
    }

    public JPanel getEnterprisePanel() {
        return enterprisePanel;
    }

    public JLabel getEmployeeCellPhoneLabel() {
        return employeeCellPhoneLabel;
    }

    public JTextField getEmployeeCellPhoneTextBox() {
        return employeeRoleTextBox;
    }

    public JPanel getEmployeeGeneralDataPanel() {
        return employeeGeneralDataPanel;
    }

    public JLabel getEmployeeNameLabel() {
        return employeeNameLabel;
    }

    public JTextField getEmployeeNameTextBox() {
        return employeeNameTextBox;
    }

    public JLabel getTitleLabel() {
        return titleLabel;
    }

    public JPanel getTitlePanel() {
        return titlePanel;
    }

    public JPanel getWindowsPanel() {
        return windowsPanel;
    }

    public JTextField getEmployeeCellPhoneTextBox1() {
        return employeeCellPhoneTextBox1;
    }

    public JTextField getEmployeeRoleTextBox() {
        return employeeRoleTextBox;
    }

    public JLabel getEmployeeRoleLabel() {
        return employeeRoleLabel;
    }

    // Variables declaration - do not modify
    private javax.swing.JButton RegisterEmployeeButton;
    private javax.swing.JButton addEnterpriseButton;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel employeeCellPhoneLabel;
    private javax.swing.JTextField employeeCellPhoneTextBox1;
    private javax.swing.JPanel employeeGeneralDataPanel;
    private javax.swing.JLabel employeeNameLabel;
    private javax.swing.JTextField employeeNameTextBox;
    private javax.swing.JLabel employeeRoleLabel;
    private javax.swing.JTextField employeeRoleTextBox;
    private javax.swing.JComboBox enterpriseComboBox;
    private javax.swing.JLabel enterpriseNameLabel;
    private javax.swing.JPanel enterprisePanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel windowsPanel;
    // End of variables declaration
}
