/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package closermeapp.Presentation.VisitorManagement;

import closermeapp.Bussiness.MemberManager.MembersManager;

import javax.swing.*;
import java.awt.event.ActionEvent;

public class MemberRegistrationView extends javax.swing.JFrame {

    /**
     * Creates new form MemberRegistrationView
     */
    public MemberRegistrationView() {
        initComponents();
        this.membershipDiscountTextBox.setText("0");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        memberGeneralDataPanel = new javax.swing.JPanel();
        memberNameLabel = new javax.swing.JLabel();
        memberNameTextBox = new javax.swing.JTextField();
        memberPhoneLabel = new javax.swing.JLabel();
        memberPhoneTextBox = new javax.swing.JTextField();
        memberCellphoneLabel = new javax.swing.JLabel();
        memberCellPhoneTextBox = new javax.swing.JTextField();
        addressSubPanel = new javax.swing.JPanel();
        memberAddressStreetLabel = new javax.swing.JLabel();
        memberAddressStreetTextBox = new javax.swing.JTextField();
        memberAddressNumberLabel = new javax.swing.JLabel();
        memberAddressNumberTextBox = new javax.swing.JTextField();
        memberAddressSidesLabel = new javax.swing.JLabel();
        memberAddressFirstSideTextBox = new javax.swing.JTextField();
        andWordLabel = new javax.swing.JLabel();
        memberAddressSecondSideTextBox = new javax.swing.JTextField();
        memberAddressNeightboorLabel = new javax.swing.JLabel();
        memberAddressNeightboorTextBox = new javax.swing.JTextField();
        membershipInformationPanel = new javax.swing.JPanel();
        membershipTypeLabel = new javax.swing.JLabel();
        membershipTypeComboBox = new javax.swing.JComboBox();
        membershipDiscountLabel = new javax.swing.JLabel();
        membershipDiscountTextBox = new javax.swing.JTextField();
        addMemberButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        memberGeneralDataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));

        memberNameLabel.setText("Nombre:");

        memberNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                memberNameTextBoxActionPerformed(evt);
            }
        });

        memberPhoneLabel.setText("Telefono: ");

        memberCellphoneLabel.setText("Celular:");

        addressSubPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dirección"));

        memberAddressStreetLabel.setText("Calle");

        memberAddressNumberLabel.setText("Numero");

        memberAddressNumberTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                memberAddressNumberTextBoxActionPerformed(evt);
            }
        });

        memberAddressSidesLabel.setText("Cruzamientos:");

        memberAddressFirstSideTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                memberAddressFirstSideTextBoxActionPerformed(evt);
            }
        });

        andWordLabel.setText("y");

        memberAddressNeightboorLabel.setText("Colonia:");

        javax.swing.GroupLayout addressSubPanelLayout = new javax.swing.GroupLayout(addressSubPanel);
        addressSubPanel.setLayout(addressSubPanelLayout);
        addressSubPanelLayout.setHorizontalGroup(
                addressSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addressSubPanelLayout.createSequentialGroup()
                                .addComponent(memberAddressStreetLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(memberAddressStreetTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(memberAddressNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(memberAddressNumberTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(memberAddressSidesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(memberAddressFirstSideTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(andWordLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(memberAddressSecondSideTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                        .addGroup(addressSubPanelLayout.createSequentialGroup()
                                .addComponent(memberAddressNeightboorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(memberAddressNeightboorTextBox))
        );
        addressSubPanelLayout.setVerticalGroup(
                addressSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addressSubPanelLayout.createSequentialGroup()
                                .addGroup(addressSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(memberAddressStreetLabel)
                                        .addComponent(memberAddressStreetTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(memberAddressNumberLabel)
                                        .addComponent(memberAddressNumberTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(memberAddressSidesLabel)
                                        .addComponent(memberAddressFirstSideTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(andWordLabel)
                                        .addComponent(memberAddressSecondSideTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addressSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(memberAddressNeightboorLabel)
                                        .addComponent(memberAddressNeightboorTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout memberGeneralDataPanelLayout = new javax.swing.GroupLayout(memberGeneralDataPanel);
        memberGeneralDataPanel.setLayout(memberGeneralDataPanelLayout);
        memberGeneralDataPanelLayout.setHorizontalGroup(
                memberGeneralDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memberGeneralDataPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(memberGeneralDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, memberGeneralDataPanelLayout.createSequentialGroup()
                                                .addComponent(memberNameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(memberNameTextBox))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, memberGeneralDataPanelLayout.createSequentialGroup()
                                                .addComponent(memberPhoneLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(memberPhoneTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(memberCellphoneLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(memberCellPhoneTextBox)))
                                .addContainerGap())
                        .addComponent(addressSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        memberGeneralDataPanelLayout.setVerticalGroup(
                memberGeneralDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(memberGeneralDataPanelLayout.createSequentialGroup()
                                .addGroup(memberGeneralDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(memberNameLabel)
                                        .addComponent(memberNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(memberGeneralDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(memberPhoneLabel)
                                        .addComponent(memberPhoneTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(memberCellphoneLabel)
                                        .addComponent(memberCellPhoneTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(addressSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        membershipInformationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Membresia"));

        membershipTypeLabel.setText("Tipo:");

        membershipTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Semanal", "Mensual", "Anual"}));
        membershipTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                membershipTypeComboBoxActionPerformed(evt);
            }
        });

        membershipDiscountLabel.setText("Descuento:");

        javax.swing.GroupLayout membershipInformationPanelLayout = new javax.swing.GroupLayout(membershipInformationPanel);
        membershipInformationPanel.setLayout(membershipInformationPanelLayout);
        membershipInformationPanelLayout.setHorizontalGroup(
                membershipInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(membershipInformationPanelLayout.createSequentialGroup()
                                .addGroup(membershipInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(membershipInformationPanelLayout.createSequentialGroup()
                                                .addComponent(membershipTypeLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(membershipTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(membershipInformationPanelLayout.createSequentialGroup()
                                                .addComponent(membershipDiscountLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(membershipDiscountTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        membershipInformationPanelLayout.setVerticalGroup(
                membershipInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(membershipInformationPanelLayout.createSequentialGroup()
                                .addGroup(membershipInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(membershipTypeLabel)
                                        .addComponent(membershipTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(membershipInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(membershipDiscountLabel)
                                        .addComponent(membershipDiscountTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        addMemberButton.setText("Agregar");
        addMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addMemberButton(evt);
            }
        });

        CancelButton.setText("Cancelar");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(memberGeneralDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(membershipInformationPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(addMemberButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(CancelButton)
                                                .addGap(50, 50, 50)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(memberGeneralDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(membershipInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addMemberButton)
                                        .addComponent(CancelButton))
                                .addGap(6, 6, 6))
        );

        pack();
    }


    private void addMemberButton(ActionEvent actionEvent) {

        String name = this.memberNameTextBox.getText();
        String phone = this.memberPhoneTextBox.getText();
        String cellphone = this.memberCellPhoneTextBox.getText();
        String address
                = this.memberAddressStreetTextBox.getText() + " "
                + this.memberAddressNumberTextBox.getText() + " "
                + this.memberAddressFirstSideTextBox.getText() + ""
                + this.andWordLabel.getText() + ""
                + this.memberAddressSecondSideTextBox.getText() + " "
                + this.memberAddressNeightboorTextBox.getText();
        String membershipType = (String) membershipTypeComboBox.getSelectedItem();
        double discount = Double.parseDouble(this.membershipDiscountTextBox.getText());

        if (!isEmptyField(name, phone, cellphone, address)) {

            sendMemberDataToManager(name, phone, cellphone, address, membershipType, discount);
        }


    }

    private void sendMemberDataToManager(String name, String phone, String cellphone, String address, String membershipType, Double discount) {
        MembersManager memberManager = MembersManager.getInstance();
            memberManager.addMember(name, phone, address, cellphone, membershipType, discount);
        showSuccessMessage();
        resetFields();
    }

    private void memberNameTextBoxActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void memberAddressNumberTextBoxActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void memberAddressFirstSideTextBoxActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void membershipTypeComboBoxActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void CancelButtonActionPerformed(ActionEvent evt) {
        this.dispose();
    }


    private boolean isEmptyField(
            String name,
            String phone,
            String cellphone,
            String address
    ) {

        if (name.equals("") ||
                phone.equals("") ||
                cellphone.equals("") ||
                address.equals("")
                ) {

            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);

            return true;
        } else {


            return false;
        }
    }

    private void showSuccessMessage() {
        JOptionPane.showMessageDialog(null, "Miembro agregado correctamente", "Agregado", JOptionPane.PLAIN_MESSAGE);
    }

    private void resetFields() {
        this.memberAddressFirstSideTextBox.setText("");
        this.memberAddressNeightboorTextBox.setText("");
        this.memberAddressNumberTextBox.setText("");
        this.memberAddressSecondSideTextBox.setText("");
        this.memberAddressStreetTextBox.setText("");
        this.memberCellPhoneTextBox.setText("");
        this.memberNameTextBox.setText("");
        this.memberPhoneTextBox.setText("");
        this.membershipDiscountTextBox.setText("");


    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberRegistrationView().setVisible(true);
            }
        });
    }


    private javax.swing.JButton CancelButton;
    private javax.swing.JButton addMemberButton;
    private javax.swing.JPanel addressSubPanel;
    private javax.swing.JLabel andWordLabel;
    private javax.swing.JTextField memberAddressFirstSideTextBox;
    private javax.swing.JLabel memberAddressNeightboorLabel;
    private javax.swing.JTextField memberAddressNeightboorTextBox;
    private javax.swing.JLabel memberAddressNumberLabel;
    private javax.swing.JTextField memberAddressNumberTextBox;
    private javax.swing.JTextField memberAddressSecondSideTextBox;
    private javax.swing.JLabel memberAddressSidesLabel;
    private javax.swing.JLabel memberAddressStreetLabel;
    private javax.swing.JTextField memberAddressStreetTextBox;
    private javax.swing.JLabel memberCellphoneLabel;
    private javax.swing.JTextField memberCellPhoneTextBox;
    private javax.swing.JPanel memberGeneralDataPanel;
    private javax.swing.JLabel memberNameLabel;
    private javax.swing.JTextField memberNameTextBox;
    private javax.swing.JLabel memberPhoneLabel;
    private javax.swing.JTextField memberPhoneTextBox;
    private javax.swing.JLabel membershipDiscountLabel;
    private javax.swing.JTextField membershipDiscountTextBox;
    private javax.swing.JPanel membershipInformationPanel;
    private javax.swing.JComboBox membershipTypeComboBox;
    private javax.swing.JLabel membershipTypeLabel;
    // End of variables declaration                   
}
