/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package closermeapp.Presentation.Views.EventManagement;

import javax.swing.*;

/**
 *
 * @author JoseJulio
 */
public class EventRegistrationView extends javax.swing.JFrame {

    /**
     * Creates new form EventRegistrationView
     */
    public EventRegistrationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        eventInformationPanel = new javax.swing.JPanel();
        eventNameLabel = new javax.swing.JLabel();
        eventNameTextBox = new javax.swing.JTextField();
        startDateLabel = new javax.swing.JLabel();
        eventStartDateTextBox = new javax.swing.JFormattedTextField();
        eventStartTimeLabel = new javax.swing.JLabel();
        eventStartTimeTextBox = new javax.swing.JFormattedTextField();
        eventEndDateLabel = new javax.swing.JLabel();
        eventEndDateTextBox = new javax.swing.JFormattedTextField();
        eventEndTimeLabel = new javax.swing.JLabel();
        eventEndTimeTextBox = new javax.swing.JFormattedTextField();
        clientInformationPanel = new javax.swing.JPanel();
        clientNameLabel = new javax.swing.JLabel();
        clientNameTextBox = new javax.swing.JTextField();
        clientPhoneLabel = new javax.swing.JLabel();
        clientPhoneTextBox = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eventInformationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del Evento"));

        eventNameLabel.setText("Nombre:");

        startDateLabel.setText("Inicia:");

        eventStartDateTextBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        eventStartDateTextBox.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        eventStartDateTextBox.setText("dd/mm/aa");

        eventStartTimeLabel.setText("a las");

        eventStartTimeTextBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        eventStartTimeTextBox.setText("hh:mm");

        eventEndDateLabel.setText("Termina:");

        eventEndDateTextBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        eventEndDateTextBox.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        eventEndDateTextBox.setText("dd/mm/aa");

        eventEndTimeLabel.setText("a las");

        eventEndTimeTextBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        eventEndTimeTextBox.setText("hh:mm");

        javax.swing.GroupLayout eventInformationPanelLayout = new javax.swing.GroupLayout(eventInformationPanel);
        eventInformationPanel.setLayout(eventInformationPanelLayout);
        eventInformationPanelLayout.setHorizontalGroup(
                eventInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(eventInformationPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(eventInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(eventInformationPanelLayout.createSequentialGroup()
                                                .addComponent(eventNameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(eventNameTextBox))
                                        .addGroup(eventInformationPanelLayout.createSequentialGroup()
                                                .addGroup(eventInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eventInformationPanelLayout.createSequentialGroup()
                                                                .addComponent(eventEndDateLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(eventEndDateTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(eventInformationPanelLayout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(startDateLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(eventStartDateTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(eventInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(eventInformationPanelLayout.createSequentialGroup()
                                                                .addComponent(eventStartTimeLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(eventStartTimeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(eventInformationPanelLayout.createSequentialGroup()
                                                                .addComponent(eventEndTimeLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(eventEndTimeTextBox)))
                                                .addGap(0, 109, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        eventInformationPanelLayout.setVerticalGroup(
                eventInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(eventInformationPanelLayout.createSequentialGroup()
                                .addGroup(eventInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(eventNameLabel)
                                        .addComponent(eventNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(eventInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(startDateLabel)
                                        .addComponent(eventStartDateTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(eventStartTimeLabel)
                                        .addComponent(eventStartTimeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(eventInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(eventEndDateLabel)
                                        .addComponent(eventEndDateTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(eventEndTimeLabel)
                                        .addComponent(eventEndTimeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        clientInformationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del Cliente"));

        clientNameLabel.setText("Nombre:");

        clientPhoneLabel.setText("Telefono:");

        javax.swing.GroupLayout clientInformationPanelLayout = new javax.swing.GroupLayout(clientInformationPanel);
        clientInformationPanel.setLayout(clientInformationPanelLayout);
        clientInformationPanelLayout.setHorizontalGroup(
                clientInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(clientInformationPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(clientInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(clientInformationPanelLayout.createSequentialGroup()
                                                .addComponent(clientNameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(clientNameTextBox))
                                        .addGroup(clientInformationPanelLayout.createSequentialGroup()
                                                .addComponent(clientPhoneLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(clientPhoneTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))))
        );
        clientInformationPanelLayout.setVerticalGroup(
                clientInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(clientInformationPanelLayout.createSequentialGroup()
                                .addGroup(clientInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(clientNameLabel)
                                        .addComponent(clientNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(clientInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(clientPhoneLabel)
                                        .addComponent(clientPhoneTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        confirmButton.setText("Confirmar");


        cancelButton.setText("Cancelar");


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(eventInformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clientInformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(confirmButton)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(eventInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clientInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cancelButton)
                                        .addComponent(confirmButton))
                                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    public JPanel getClientInformationPanel() {
        return clientInformationPanel;
    }

    public void setClientInformationPanel(JPanel clientInformationPanel) {
        this.clientInformationPanel = clientInformationPanel;
    }

    public JButton getCancelButton() {
        return cancelButton;
    }

    public void setCancelButton(JButton cancelButton) {
        this.cancelButton = cancelButton;
    }

    public JTextField getClientNameTextBox() {
        return clientNameTextBox;
    }

    public void setClientNameTextBox(JTextField clientNameTextBox) {
        this.clientNameTextBox = clientNameTextBox;
    }

    public JTextField getClientPhoneTextBox() {
        return clientPhoneTextBox;
    }

    public void setClientPhoneTextBox(JTextField clientPhoneTextBox) {
        this.clientPhoneTextBox = clientPhoneTextBox;
    }

    public JButton getConfirmButton() {
        return confirmButton;
    }

    public void setConfirmButton(JButton confirmButton) {
        this.confirmButton = confirmButton;
    }

    public JFormattedTextField getEventEndDateTextBox() {
        return eventEndDateTextBox;
    }

    public void setEventEndDateTextBox(JFormattedTextField eventEndDateTextBox) {
        this.eventEndDateTextBox = eventEndDateTextBox;
    }

    public JFormattedTextField getEventEndTimeTextBox() {
        return eventEndTimeTextBox;
    }

    public void setEventEndTimeTextBox(JFormattedTextField eventEndTimeTextBox) {
        this.eventEndTimeTextBox = eventEndTimeTextBox;
    }

    public JPanel getEventInformationPanel() {
        return eventInformationPanel;
    }

    public void setEventInformationPanel(JPanel eventInformationPanel) {
        this.eventInformationPanel = eventInformationPanel;
    }

    public JTextField getEventNameTextBox() {
        return eventNameTextBox;
    }

    public void setEventNameTextBox(JTextField eventNameTextBox) {
        this.eventNameTextBox = eventNameTextBox;
    }

    public JFormattedTextField getEventStartDateTextBox() {
        return eventStartDateTextBox;
    }

    public void setEventStartDateTextBox(JFormattedTextField eventStartDateTextBox) {
        this.eventStartDateTextBox = eventStartDateTextBox;
    }

    public JFormattedTextField getEventStartTimeTextBox() {
        return eventStartTimeTextBox;
    }

    public void setEventStartTimeTextBox(JFormattedTextField eventStartTimeTextBox) {
        this.eventStartTimeTextBox = eventStartTimeTextBox;
    }

    public JLabel getStartDateLabel() {
        return startDateLabel;
    }

    public void setStartDateLabel(JLabel startDateLabel) {
        this.startDateLabel = startDateLabel;
    }

    public JLabel getEventStartTimeLabel() {
        return eventStartTimeLabel;
    }

    public void setEventStartTimeLabel(JLabel eventStartTimeLabel) {
        this.eventStartTimeLabel = eventStartTimeLabel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventRegistrationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel clientInformationPanel;
    private javax.swing.JLabel clientNameLabel;
    private javax.swing.JTextField clientNameTextBox;
    private javax.swing.JLabel clientPhoneLabel;
    private javax.swing.JTextField clientPhoneTextBox;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel eventEndDateLabel;
    private javax.swing.JFormattedTextField eventEndDateTextBox;
    private javax.swing.JLabel eventEndTimeLabel;
    private javax.swing.JFormattedTextField eventEndTimeTextBox;
    private javax.swing.JPanel eventInformationPanel;
    private javax.swing.JLabel eventNameLabel;
    private javax.swing.JTextField eventNameTextBox;
    private javax.swing.JFormattedTextField eventStartDateTextBox;
    private javax.swing.JLabel eventStartTimeLabel;
    private javax.swing.JFormattedTextField eventStartTimeTextBox;
    private javax.swing.JLabel startDateLabel;
    // End of variables declaration                   
}
