package closermeapp.Presentation.Views.Report;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;

/**
 *
 * @author André
 */
public class ReportView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalMenu
     */
    public ReportView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        windowsPanel = new javax.swing.JPanel();
        monthReportPanel = new javax.swing.JPanel();
        generateMonthReportButton = new javax.swing.JButton();
        generateReporLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        selectDateLabel = new javax.swing.JLabel();
        weeklyReportPanel = new javax.swing.JPanel();
        generateWeeklyReportButton = new javax.swing.JButton();
        generateWeeklyButton = new javax.swing.JLabel();
        todaysReportPanel = new javax.swing.JPanel();
        generateTodaysReport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        monthReportPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        generateMonthReportButton.setText("Generar");

        generateReporLabel.setText("Generar reporte mensual");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel());

        selectDateLabel.setText("Selecciona una Fecha");

        javax.swing.GroupLayout monthReportPanelLayout = new javax.swing.GroupLayout(monthReportPanel);
        monthReportPanel.setLayout(monthReportPanelLayout);
        monthReportPanelLayout.setHorizontalGroup(
                monthReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(monthReportPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(monthReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(selectDateLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(monthReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monthReportPanelLayout.createSequentialGroup()
                                                .addComponent(generateMonthReportButton)
                                                .addGap(48, 48, 48))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monthReportPanelLayout.createSequentialGroup()
                                                .addComponent(generateReporLabel)
                                                .addGap(21, 21, 21))))
        );
        monthReportPanelLayout.setVerticalGroup(
                monthReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monthReportPanelLayout.createSequentialGroup()
                                .addContainerGap(23, Short.MAX_VALUE)
                                .addComponent(generateReporLabel)
                                .addGap(18, 18, 18)
                                .addComponent(generateMonthReportButton)
                                .addGap(22, 22, 22))
                        .addGroup(monthReportPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(selectDateLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        weeklyReportPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        generateWeeklyReportButton.setText("Generar");

        generateWeeklyButton.setText("Generar reporte semanal");

        javax.swing.GroupLayout weeklyReportPanelLayout = new javax.swing.GroupLayout(weeklyReportPanel);
        weeklyReportPanel.setLayout(weeklyReportPanelLayout);
        weeklyReportPanelLayout.setHorizontalGroup(
                weeklyReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(weeklyReportPanelLayout.createSequentialGroup()
                                .addGroup(weeklyReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(weeklyReportPanelLayout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addComponent(generateWeeklyReportButton))
                                        .addGroup(weeklyReportPanelLayout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(generateWeeklyButton)))
                                .addContainerGap(23, Short.MAX_VALUE))
        );
        weeklyReportPanelLayout.setVerticalGroup(
                weeklyReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, weeklyReportPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(generateWeeklyButton)
                                .addGap(18, 18, 18)
                                .addComponent(generateWeeklyReportButton)
                                .addGap(30, 30, 30))
        );

        todaysReportPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        generateTodaysReport.setText("Generar");

        jLabel1.setText("Generar Reporte de hoy");

        javax.swing.GroupLayout todaysReportPanelLayout = new javax.swing.GroupLayout(todaysReportPanel);
        todaysReportPanel.setLayout(todaysReportPanelLayout);
        todaysReportPanelLayout.setHorizontalGroup(
                todaysReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todaysReportPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(generateTodaysReport)
                                .addGap(67, 67, 67))
                        .addGroup(todaysReportPanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel1)
                                .addContainerGap(36, Short.MAX_VALUE))
        );
        todaysReportPanelLayout.setVerticalGroup(
                todaysReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todaysReportPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(generateTodaysReport)
                                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout windowsPanelLayout = new javax.swing.GroupLayout(windowsPanel);
        windowsPanel.setLayout(windowsPanelLayout);
        windowsPanelLayout.setHorizontalGroup(
                windowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(windowsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(monthReportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(weeklyReportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, windowsPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(todaysReportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165))
        );
        windowsPanelLayout.setVerticalGroup(
                windowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(windowsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(windowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(monthReportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(weeklyReportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addComponent(todaysReportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(windowsPanel);

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportView().setVisible(true);
            }
        });
    }

    public JButton getGenerateMonthReportButton() {
        return generateMonthReportButton;
    }

    public JLabel getGenerateReporLabel() {
        return generateReporLabel;
    }

    public JButton getGenerateTodaysReport() {
        return generateTodaysReport;
    }

    public JLabel getGenerateWeeklyButton() {
        return generateWeeklyButton;
    }

    public JButton getGenerateWeeklyReportButton() {
        return generateWeeklyReportButton;
    }

    public JComboBox getjComboBox1() {
        return jComboBox1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JPanel getMonthReportPanel() {
        return monthReportPanel;
    }

    public JLabel getSelectDateLabel() {
        return selectDateLabel;
    }

    public JPanel getTodaysReportPanel() {
        return todaysReportPanel;
    }

    public JPanel getWeeklyReportPanel() {
        return weeklyReportPanel;
    }

    public JPanel getWindowsPanel() {
        return windowsPanel;
    }


    // Variables declaration - do not modify
    private javax.swing.JButton generateMonthReportButton;
    private javax.swing.JLabel generateReporLabel;
    private javax.swing.JButton generateTodaysReport;
    private javax.swing.JLabel generateWeeklyButton;
    private javax.swing.JButton generateWeeklyReportButton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel monthReportPanel;
    private javax.swing.JLabel selectDateLabel;
    private javax.swing.JPanel todaysReportPanel;
    private javax.swing.JPanel weeklyReportPanel;
    private javax.swing.JPanel windowsPanel;
    // End of variables declaration
}
